sudo: required
language: node_js
node_js:
  - "8.5"
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - docker login -u "$HEROKU_USERNAME" -p $HEROKU_PASSWORD registry.heroku.com

install:
  - docker build -t quyencm/nginx-docker-react .
  - docker build -t quyencm/docker-react --file Dockerfile.dev .

script:
  - docker run quyencm/docker-react npm run test -- --coverage 
  - docker tag quyencm/nginx-docker-react registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: heroku
  run:
    - "docker push registry.heroku.com/$HEROKU_APP_NAME/web"
    - "heroku container:release web --app $HEROKU_APP_NAME"
  on:
    branch: master