sudo: required
language: node_js
node_js:
  - "8.5"
services:
  - docker

before_install:
  - docker build -t quyencm/docker-react --file Dockerfile.dev .

script:
  - docker run quyencm/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key: 
    secure: "$API_KEY"
  app: "docker-react-2"
  on:
    branch: master