sudo: required
language: node_js
node_js:
  - "iojs"
  - "7"
services:
  - docker

before_install:
  - docker build -t quyencm/docker-react --file Dockerfile.dev .

script:
  - docker run quyencm/docker-react npm run test -- --coverage